language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4

env:
  global:
    - setup=basic

matrix:
  fast_finish: true

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

script: vendor/bin/phpunit
